name: CICD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -S . -B ./build/
    - name: make
      run: cd build && make
    - name: test
      run: ./build/tests/number_tests
